POST http://localhost:7071/api/purchase
    
{
    "productId": 4,
    "quantity": 100,
    "customerName": "Prasanna",
    "customerEmail": "prasannarena@gmail.com",
    "purchasePrice": 10001.00
 }

####

GET http://localhost:7071/api/purchase/37c63b30-bcbd-466f-8da2-4efc0a317754

#### Start a new orchestration

GET http://localhost:7071/api/NewOrderOrchestration_HttpStart?price=800

#Send external event
POST http://localhost:7071/api/NewOrderOrchestration_Approve?id=e2cda9a15a434716bdf19e7b24003dd3

{
    "IsApproved": true,
    "ApprovedBy": "Prasanna"
}


### Check on a specific instance

GET http://localhost:7071/runtime/webhooks/durabletask/instances/24f46a2ec4cf44ed9c0ce7fe9274beac?code=YOUR_CODE_HERE
